### ISSUE TITLE
Python 3.12 unit tests

### ISSUE THREAD

**Issue by intentionally-left-nil** [rnag/dataclass-wizard#103]
* Dataclass Wizard version: main
* Python version: 3.12
* Operating System: mac

### Description
There are many pytest failures when running against python 3.12. I am happy to take a look and try to clean them up. However, can you first confirm that a PR would be welcome and have a path forwards to merging? Otherwise I'm not inclined to do the work

**Comment by rnag** [comment]
Hi @intentionally-left-nil , thanks for opening this issue. I apologize as I have been on a long hiatus from the project. I recently installed Python 3.12 on my new Mac and tried running pytest cases, and also encountered the same issues. 

If you are able to take a look, I would certainly welcome a PR to make the code and tests compatible with python 3.12. Otherwise, I will take a look when I have time, and do some local debugging to see how to best update code to support latest python versions.

**Comment by rnag** [comment]
Closed by #107 

`v0.22.3` is now available on PyPI!

**Comment by rnag** [comment]
Closed by #107 

`v0.22.3` is now available on PyPI!
