### ISSUE TITLE
datetime.timedelta support

### ISSUE THREAD

**Issue by LEv145** [rnag/dataclass-wizard#23]
* Dataclass Wizard version: `0.15.2`
* Python version: `3.9`
* Operating System: `linux`

### Description

I suggest adding `datetime.timedelta` support for load and dump

**Comment by rnag** [comment]
Hi @LEv145, just an update but the latest version [0.16.0](https://pypi.org/project/dataclass-wizard/0.16.0/) should now add support for `datetime.timedelta`. This leverages the `pytimeparse` library as noted above for parsing a string as a `timedelta` object. Also a note that the load logic turned out a bit more complicated than above, since I figured we also need to check if it's a numeric value instead, representing the total seconds.  You can view the diff [here](https://github.com/rnag/dataclass-wizard/pull/24/files).

I also didn't want to add a dependency for `pytimeparse` by default, so I've currently added it as a bonus feature which can be installed if needed. To enable `timedelta` support you can use the following syntax:

```
pip install dataclass-wizard[timedelta]
```

**Comment by LEv145** [comment]
Cool

**Comment by LEv145** [comment]
I thought it might be better to store `timedelta` as a number with an indicator of seconds, as done in youtube-dl
Then `pytimeparse` is not needed

**Comment by rnag** [comment]
Yep, definitely agree on that. If you check how we're actually converting a value to `timedelta` here [here](https://github.com/rnag/dataclass-wizard/blob/main/dataclass_wizard/utils/type_conv.py#L315), it's initially calling `pytimeparse.parse` as the assumption is it's generally a string, but I agree that it might be better to explicitly check if its a numeric type first; that way we won't need to the `pytimeparse` import at all, as you mentioned.

**Comment by rnag** [comment]
@LEv145 I've added a minor refactor to how we parse strings or numbers to `timedelta` in [v0.20.3](https://github.com/rnag/dataclass-wizard/pull/38/files), so that we can avoid calling `pytimeparse` if it appears to be a numeric value.

Though, I realized I might have been misunderstanding it earlier. I guess you were talking about how `timedelta` values as serialized, since right now we just call `str()` method on these objects; the only issue with this approach, as I now realize that when de-serializing this data, we will need to call `pytimeparse.parse` each time to resolve them to `timedelta` objects again.

At this point, I think it's not the best idea to change the default behavior of how timedelta objects are serialized -- however, I would be happy with adding a bool attribute to the ``Meta`` config, something like `marshal_timedelta_as_number`, so that timedelta objects can be serialized as `float` values by default -- this should ensure that we don't require the `pytimeparse` module for de-serialization again, and should actually be faster in this case, now that I think about it.
