### ISSUE TITLE
Question/feature request: Map a (nested) JSON/dict Key to a Field

### ISSUE THREAD

**Issue by iwconfig** [rnag/dataclass-wizard#60]
It is [possible to map JSON keys to fields ](https://dataclass-wizard.readthedocs.io/en/latest/common_use_cases/custom_key_mappings.html)with different names. However, I would like to map nested JSON/dict by key path, preferably by dot-delimited strings

```python3
'parent.child.grandchild[1].sibling'
```
or as lists of keys
```python3
['parent', 'child', 'grandchild', 1, 'sibling']
```

So it would look something like

```python3
class Meta(JSONSerializable.Meta):
        json_key_to_field = {
            'parent.child.grandchild[1].sibling': 'my_str'
        }
```

or

```python3
json_field(
        ('myJSONKey',
         'parent.child.grandchild[1].sibling',
         ('parent2', 'child', 'grandchild', 4, 'sibling'),
         'myField'
)
```

As of yet, I have not been able to come up with a way to accomplish this with `dataclass-wizard`. Do you know if this is currently possible? If not, is it something you would consider implementing?

Thank you for a terrific module btw!

**Comment by rnag** [comment]
Hi @iwconfig, thanks for opening this issue! I agree that a feature request for a nested JSON path traversal is certainly an interesting one, and one that is worth supporting. I've actually added a [milestone](https://github.com/rnag/dataclass-wizard/milestone/5) a while back to help track this feature, but it is definitely one that I have plans to implement in one of the upcoming releases.

I will keep this thread updated as I make more progress towards the request. In any case, I've also added a 'help wanted' label to this issue in case anyone wants to take a stab at implementing the feature at well.

**Comment by iwconfig** [comment]
Oh, I didn't see that milestone, sorry. That's great!

Wow, awesome! What you've got there is just for paths separated into a list, right? I know [fnc](https://fnc.readthedocs.io) and [pydash](https://pydash.readthedocs.io) (same author) also offers this functionality, and can handle dot-delimited paths as well. Maybe you'll find something interesting in how they do it. `pydash` is more mature but `fnc` is faster due to generator based approach.

Thank you for this! :1st_place_medal:

**Comment by rnag** [comment]
@iwconfig sorry for the delay in moving this forward - got busy with life.

Thanks for the suggestions! I updated my benchmark code to test with `fnc` and `pydash` as mentioned. Also you are correct, those are just for paths already separated into a list. For parsing a dot-delimited string into a list, I might need another library for that (or just create one 🤔 ).

Going to look into this shortly when time allows, as I will have some bandwidth for it due to the holiday season coming up.

**Comment by rnag** [comment]
@iwconfig Hi there 👋 , hope everything's going well!

Thank you again for this feature request, because it is a really useful feature, and I am glad to finally support it finally in `v0.29.0`! 🎉 

Apologies that it took a while for me to look into this, and I'll admit a large part of my impetus was usage in my [toy project](https://github.com/rnag/GMU-Daily-Permit-Automation) which I'm using for personal/school purposes.

In any case, the [main docs](https://dataclass-wizard.readthedocs.io/en/latest/#mapping-nested-json-keys) now mention this feature, and I have even added a dedicated section in the docs on how to [Map a Nested JSON Key Path to a Field](https://dataclass-wizard.readthedocs.io/en/latest/common_use_cases/nested_key_paths.html)!
